---
- name: Make Service Up
  hosts: localhost
  tasks:
    - name: Remove old images
      shell:
        cmd: |
          docker rmi rushikesh0203/virtuallab_frontend:latest
          docker rmi rushikesh0203/virtuallab_backend:latest
          docker rmi rushikesh0203/virtuallab_db:latest
          docker rmi rushikesh0203/virtuallab_mongodb:latest
    - name: Stop Containers if any
      shell:
        cmd: |
          docker stop frontend
          docker stop backend
          docker stop db
          docker stop mongodb
          docker stop instituionserver
      ignore_errors: yes
    - name: Remove Containers if any
      shell:
        cmd: |
          docker rm frontend
          docker rm backend
          docker rm db
          docker rm mongodb
          docker rm insitituionserver
      ignore_errors: yes

    - name: Start the Service
      shell:
        cmd: docker-compose -f ./../docker-compose.yml up -d
      ignore_errors: yes
