---
- name: Make Service Down
  hosts: localhost
  tasks:
    - name: Stop the Service
      shell:
        cmd: docker-compose -f ./../docker-compose.yml down -d
    - name: Remove old images
      shell:
        cmd: |
          docker rmi rushikesh0203/virtuallab_frontend:latest
          docker rmi rushikesh0203/virtuallab_backend:latest
          docker rmi rushikesh0203/virtuallab_db:latest
          docker rmi rushikesh0203/virtuallab_mongodb:latest