---
- name: Perfrom a specific task in the container
  hosts: Institution_Host
  vars:
    labName: "{{ labName }}"
    sourcePath: "{{ sourcePath }}"
    destPath: "{{ destPath }}"
    fileName: "{{ fileName }}"
  tasks:
    - name: Start Container
      shell:
        cmd: docker start {{labName}}
    - name: Copy output file
      copy:
        src: "{{ sourcePath }}"
        dest: "{{ fileName }}"
    - name: Copy file
      shell:
        cmd: docker cp {{fileName}} {{destPath}}
