---
- name: Perfrom a specific task in the container
  hosts: Institution_Host
  vars:
    labName: "{{ labName }}"
    sourcePath: "{{ sourcePath }}"
    destPath: "{{ destPath }}"
  tasks:
    - name: Start Container
      shell:
        cmd: docker start {{labName}}
    - name: Copy output file
      fetch:
        src: "{{ sourcePath }}"
        dest: execise_file
        flat: yes
    - name: Copy file
      shell:
        cmd: docker cp execise_file {{destPath}}