---
- name: Perfrom a specific task in the container
  hosts: Institution_Host
  vars:
    labName: "{{ labName }}"
    sourcePath: "{{ sourcePath }}"
    destPath: "{{ destPath }}"
  tasks:
    - name: Start Container
      shell:
        cmd: docker start {{labName}}
    - name: Copy file
      shell:
        cmd: docker cp {{sourcePath}} {{destPath}}